### ISSUE TITLE
前端打包抱错

### ISSUE THREAD

**Issue by ba370921** [edp963/davinci#2272] opened 2021-11-10 06:44 UTC
![image](https://user-images.githubusercontent.com/16890445/141063203-8080b112-6192-4b9c-8c30-d74e9017a2d9.png)

**Comment by ba370921** [comment] 2021-11-10 06:44
下载以后没动任何代码

**Comment by scottsut** [comment] 2021-11-10 10:22
Duplicate of #1985

**Closed as completed by scottsut** 2021-11-10 10:22 UTC
