### ISSUE TITLE
when I try to create view, I find a bug

### ISSUE THREAD

**Issue by chinadragon009** [edp963/davinci#799] opened 2019-03-27 01:05 UTC
this is detail,when I choose a  datasource , the  "Execution" button   is disappeard
![image](https://user-images.githubusercontent.com/32754947/55042976-0bbc6a00-506f-11e9-97d3-b89c0a4b5ecb.png)

I  have to  fitler the datasource ,to use  the "Execution" button 

![image](https://user-images.githubusercontent.com/32754947/55043067-63f36c00-506f-11e9-844b-a1174e74ee7a.png)

**Comment by scottsut** [comment] 2019-04-04 06:36
Caused by Chrome updates
#722 
#723

**Comment by AndyFong** [comment] 2019-05-30 07:28
fixed in Beta-5 version

**Closed by AndyFong** 2019-05-30 07:28 UTC
