### ISSUE TITLE
Click on the map to drill report an error

### ISSUE THREAD

**Issue by h920553245** [edp963/davinci#1724] opened 2020-05-19 06:18 UTC
I used 2 indicators which one is a provinces and the other is a cities. Draw a map using provinces as latitudes. move mouse on map, right click , report error
![image](https://user-images.githubusercontent.com/26131504/82291346-6505fc00-99db-11ea-9803-e45f1bdc6fb2.png)
![image](https://user-images.githubusercontent.com/26131504/82291406-7cdd8000-99db-11ea-8362-4ad897ddebad.png)
![image](https://user-images.githubusercontent.com/26131504/82291451-8ebf2300-99db-11ea-86b0-2bc14018a101.png)

**Comment by scottsut** [comment] 2020-05-19 06:21
Duplicate of #1713

**Closed by scottsut** 2020-05-19 06:21 UTC
