### ISSUE TITLE
kylin 做数据源的时候，图表添加颜色 sql 报错

### ISSUE THREAD

**Issue by wangwei465** [edp963/davinci#1630] opened 2020-04-03 14:49 UTC
用kylin做数据源时，当对可视化图表添加颜色的时候，会报sql错误：Column xxxx is ambiguous
eg:
SELECT
 "性别","性别"
,
 count("sid") AS "count(sid)"
FROM (SELECT sid, (CASE SEX WHEN 1 THEN '男' ELSE '女' END) as 性别  FROM studentinfo) T
GROUP BY "性别","性别"

**Comment by scottsut** [comment] 2020-04-06 01:18
Duplicate of #1336

**Closed by scottsut** 2020-04-06 01:18 UTC
