### ISSUE TITLE
提几个bug,

### ISSUE THREAD

**Issue by mstaryi** [edp963/davinci#1023] opened 2019-06-18 10:35 UTC
我装的是docker版本,浏览器版本是Chrome 74.0.3729.169
1. 添加数据源时，类型选择csv文件时窗口还是jdbc的填写项
2. 添加视图时，输入SQL点“执行”按钮后窗口进入空页面，弹出“Syntax check Success”提示，啥也干不了，也退不回去

**Comment by AndyFong** [comment] 2019-06-18 14:51
1. This is not a bug, when choose the source type to `csv`, it means providing a jdbc supported database to store the csv files data when upload csv files in `Davinci`, so the jdbc info is also required.  
2. Please post the screenshot or gif.

**Comment by mstaryi** [comment] 2019-06-19 02:12
![bug](https://user-images.githubusercontent.com/26699467/59731933-bf9e5180-927a-11e9-9839-07ab6fe4353b.gif)
this is the screenshot

**Comment by AndyFong** [comment] 2019-06-19 03:09
This bug is already fixed in branch `dev-0.3`, we will publish it soon.

**Comment by AndyFong** [comment] 2019-06-23 05:14
fixed in beta 6 version.  
https://github.com/edp963/davinci/releases/tag/v0.3.0-beta.6

**Closed** 2019-06-23 05:14 UTC
