### ISSUE TITLE
指标自定义count做成指标要怎么做?

### ISSUE THREAD

**Issue by gclsoft** [edp963/davinci#1638] opened 2020-04-11 09:35 UTC
```
Select 
T.Fcontrolunitid Ou,--Decode(T.Fsourcetype,'搜索引擎','11','14') Bt2,  -- 11=竞价,14=无轨迹
Count(  (Case When T.Fcustomersendmessagenum>0 And T.Finitialcustomerservice Is Not Null
                  Then T.Fcustomerimportid||To_char(T.Faccesstime,'yyyy-mm-dd')  Else Null End)) Dhl,--对话量
Count( Distinct (Case When T.Fcustomersendmessagenum>0  And T.Fconsulttype='1'
                  And T.Finitialcustomerservice Is Not Null
                  --And T.Fsourcetype='搜索引擎'  
                  Then T.Fcustomerimportid||To_char(T.Faccesstime,'yyyy-mm-dd')  Else Null End)) Dljjdhl,--有效对话量
Count(Distinct (Case When T.Finvalidtype In ('11','12','13') And T.Fconsulttype='1'
                Then T.Fcustomerimportid||To_char(T.Faccesstime,'yyyy-mm-dd') Else Null End)) Zxl ,--咨询量
Count(Distinct (Case When T.Finvalidtype ='11' And T.Fconsulttype='1'
                Then T.Fcustomerimportid||To_char(T.Faccesstime,'yyyy-mm-dd')  Else Null End)) Zxl_New --新客咨询量                          
  From T_Crm_Businesscustomer T
   Where T.Fcontrolunitid ='rhtEWfsQRFqthMznrtQ='
       And T.Faccesstime >= To_Date ('2020-04-01', 'YYYY-MM-DD')
        And T.Faccesstime < To_Date ('2020-04-01', 'YYYY-MM-DD') +  1
       --  And T.Fconsulttype='1'
 Group By  (T.Fcontrolunitid)
```
Count(Distinct (Case When T.Finvalidtype In ('11','12','13') And T.Fconsulttype='1'
                Then T.Fcustomerimportid||To_char(T.Faccesstime,'yyyy-mm-dd') Else Null End)) Zxl ,
像这种比较复杂的count, 要怎么做成指标?
像superset那样填入自定义的count可以吗?
![image](https://user-images.githubusercontent.com/1269898/79040391-af48d000-7c1a-11ea-9768-af28d62f82e7.png)

**Comment by scottsut** [comment] 2020-04-11 13:05
Duplicate of #1252

**Closed by scottsut** 2020-04-11 13:05 UTC
