### ISSUE TITLE
In version 0.3, when the front end deploys itself, the display page does not have a property panel.

### ISSUE THREAD

**Issue by sq8852161** [edp963/davinci#816] opened 2019-04-09 06:53 UTC
![davinci-display](https://user-images.githubusercontent.com/9211058/55779118-3d095100-5ad7-11e9-89f7-c8a17c31716a.PNG)

**Comment by scottsut** [comment] 2019-04-11 11:49
Caused by chrome updates, will fix in next release.

**Comment by AndyFong** [comment] 2019-05-30 07:29
Fixed in 0.3.0-beta-5 version

**Closed by AndyFong** 2019-05-30 07:30 UTC
